version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /conformance-tests
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /integration-tests
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /mcp-client
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /mcp-external-validation
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /examples/ui-enabled-server/ui
    schedule:
      interval: weekly
    labels:
      - dependencies
