[package]
name = "simple-mcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use the official MCP SDK for proper protocol compliance
rmcp = "0.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"

[[bin]]
name = "simple-mcp-server"
path = "src/main.rs"