[package]
name = "profiling-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
pulseengine-mcp-server = { path = "../../mcp-server" }
pulseengine-mcp-protocol = { path = "../../mcp-protocol" }
pulseengine-mcp-logging = { path = "../../mcp-logging" }
pulseengine-mcp-auth = { path = "../../mcp-auth" }
pulseengine-mcp-monitoring = { path = "../../mcp-monitoring" }

tokio = { version = "1.25", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
rand = "0.8"
uuid = { version = "1.0", features = ["v4", "serde"] }

[[bin]]
name = "profiling-demo"
path = "src/main.rs"

[[bin]]
name = "simple-demo"
path = "src/simple_demo.rs"